os: linux
dist: bionic
language: java
install: true
jdk:
  - openjdk8
  - openjdk9
  - openjdk10
  - openjdk11
  - openjdk12
  - openjdk13
  - openjdk14
cache:
  directories:
    - $HOME/.m2
script: ./mvnw clean verify -U
